### ISSUE TITLE
index.d.ts declarations missing as of v1.8.1

### ISSUE THREAD

**Issue by resir014** [thearnica/react-media-match#10]
I just realised from the [built packages](https://unpkg.com/react-media-match@1.8.1/) that the `index.d.ts` files are missing from both the es5 and the es2015 bundles, making the typings break from version 1.8.1 since TS can't load them.

<img width="1012" alt="Screen Shot 2019-03-10 at 10 21 31" src="https://user-images.githubusercontent.com/5663877/54080270-9f2b3680-431e-11e9-95aa-f3c3ef2ae63a.png">

For reference, the previous version's bundle (1.8.0) looked like this:

<img width="1012" alt="Screen Shot 2019-03-10 at 10 22 14" src="https://user-images.githubusercontent.com/5663877/54080273-b702ba80-431e-11e9-8f39-a7c4dfb387a5.png">

**Comment by theKashey** [comment]
Oh, and the last commit was mine...

**Comment by thearnica** [comment]
I've just checked - it supposed to be so. Index file does not contain any types, only references to the files they are defined in.
And I could not see any TypeScript related issues - it just works.

Could you please be more concrete? What does TS says?

**Comment by thearnica** [comment]
.... 🙀, complication failed. 😤, @theKashey

**Comment by thearnica** [comment]
Thank you for a report 1.8.2 released.

**Comment by resir014** [comment]
> Could you please be more concrete? What does TS says?

Because TypeScript couldn't find the `index.d.ts`, which is explicitly set in the `types` key of `package.json`, it returns a `Could not find module` error.

And thanks for the fix @theKashey @thearnica! It now works. ❤️
