### ISSUE TITLE
Predicted value overwrite values by window.matchMedia

### ISSUE THREAD

**Issue by randy-ang** [thearnica/react-media-match#46]
Hello, I've encountered an issue where sometimes window.matchMedia value is merged with prefetched value and results in multiple matched keys becoming true. This results in sometimes the view not adjusting with the media.

If the predicted value of the ssr is equal to the first item in the queries passed to `createMediaMatcher`, then it won't render to anything other than the predicted value (even if screen size changes).

issue example 
```
import React from 'react'
import { createMediaMatcher } from 'react-media-match'

const mobile = <div>mobile rendered</div>
const desktop = <div>desktop rendered</div>

const queries = {
  mobile: '(max-width: 767px)',
  desktop: '(min-width: 768px)',
}

// this only happens if predicted is equal first key of the queries
const [predicted] = Object.keys(queries)

const { Provider, Matcher, ServerRender } = createMediaMatcher(queries)

const ResponsiveViewComponent = () => {
  return (
    <Provider>
      <ServerRender predicted={predicted} hydrated>
        <Matcher mobile={mobile} desktop={desktop} />
      </ServerRender>
    </Provider>
  )
}
```

I've identified the problem and found that this is because when passing value from the provider, it uses the value from window.matchMedia, and then append value from the parentMatch (in this case { [predicted]: true }).

```
// createMediaMatcher.tsx
// ...
  const ProvideMediaMatchers: React.SFC<{ state?: BoolOf<T> }> = ({children, state = null}) => (
    <MediaContext.Consumer>
      {(parentMatch: any) =>
        <Media queries={breakPoints}>
          {(matches) => {
           // value from window.matchMedia is overridden by parent value
            const value: BoolOf<T> = state || {
              ...notNulls(matches),
              ...(parentMatch || {}), // this should be on top so that window.matchMedia values are used 
            };
            return <MediaContext.Provider
              value={value}
              children={children}
            />
          }}
        </Media>
      }
    </MediaContext.Consumer>
  );
```

I've forked the repo and fixed the bug. If it's alright with you guys I want to create a pr to fix this issue. thanks.

**Comment by theKashey** [comment]
Hey! Thank you for the fix. Look like the current behaviour is not correct. However, I am not sure that you actually fixed it.

The idea is:
- to provide a value to be used during SSR
- "hydrate" into that value
- and then __reject it completely__ and use the real matches.

That means - the fix should not be in `ProvideMediaMatchers` but in `ServerRender`

**Comment by randy-ang** [comment]
yes the bug is in `ServerRender`, but as seen from the code below, the component `ServerRender` actually contains the component `ProvideMediaMatchers` that is provided with the value `{ [predicted]: true }` by the `ServerRender`. This value is actually the `parentMatch` for `ProvideMediaMatchers` and will overwrite the value provided by window.matchMedia, thus causing the bug. 

```
const ServerRender: React.SFC<{ predicted: keyof T, hydrated?: boolean, children: React.ReactNode }> = ({predicted, hydrated, children}) => (
     // {[predicted]: true} is passed as parentMatch to ProvideMediaMatchers here
    <MediaContext.Provider value={{[predicted]: true} as BoolOf<T>}>
      <ProvideMediaMatchers>
        <MediaContext.Consumer>
          {matched => (
            <MediaServerSide
              fact={getMaxMatch(breakPoints, matched)}
              predicted={predicted}
              hydrated={!!hydrated}
              children={children}
            />
          )}
        </MediaContext.Consumer>
      </ProvideMediaMatchers>
    </MediaContext.Provider>
  );
```

**Comment by theKashey** [comment]
Good catch! That's means that your change is absolutely correct (but I have to add some tests to double check and prevent the same fuckup in the future)

**Comment by theKashey** [comment]
This is the code I use nowadays 
- using `Override` __after__ Providers
- removing Override after initial hydration

```tsx
const makeAllFalse = (keys: string[]) =>  keys.reduce((acc,key)=>{
 acc[key]=false;
 return acc;
}, {});

export const MediaProvider: FC = ({ children, predicted }) => {
	const [override, setOverride] = useState({
               ...makeAllFalse(Object.keys(breakpoints.queries))
		[predicted]: true,
	});

	useEffect(() => {
               // remove override after mount
		setOverride({} as any);
	}, []);

	return (
		<MediaPointProvider>
			<MediaPointOverride {...override}>{children}</MediaPointOverride>
		</MediaPointProvider>
	);
};

```

the existing `MediaServerSide` has to be rewritten :(

**Comment by theKashey** [comment]
PR drafted. As usual, it's way simpler to implement some things from the inside.

**Comment by tjjjwxzq** [comment]
Awesome @theKashey , thank you for the fix 😸  🎉
