### ISSUE TITLE
After upgrading from 1.13.0 -> 1.14.2 react-media-match/targets is no longer available

### ISSUE THREAD

**Issue by slevens-atlas** [thearnica/react-media-match#90]
I see in this commit https://github.com/thearnica/react-media-match/commit/beb757999c62c67cb0bc1c4f80a6cfbcc8b7b08a#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

The targets directory was removed from the build output. 

According to the documentation https://github.com/thearnica/react-media-match/commit/beb757999c62c67cb0bc1c4f80a6cfbcc8b7b08a#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519 you are still meant to be importing from /targets

Can we add back in the build output for targets or update the documentation on the correct usage. 🥂

**Comment by theKashey** [comment]
😯 I do think that was intentional. Just new defaults from updated bundler and it’s gone. 

Let’s bring it back

**Comment by thearnica** [comment]
targets has been restored in v1.14.4. Thanks for reporting the defect Sam 👋

**Comment by slevens-atlas** [comment]
Thanks team :D
